# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('heading_date', models.CharField(default='Date', max_length=50)),
                ('heading_text', models.CharField(default='Description', max_length=50)),
                ('heading_in', models.CharField(default='Money In', max_length=50)),
                ('heading_out', models.CharField(default='Money Out', max_length=50)),
                ('heading_balance', models.CharField(default='Balance', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('trans_date', models.DateField()),
                ('net_input', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('verbose_description', models.CharField(max_length=200)),
                ('trans_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('money_in', models.DecimalField(decimal_places=2, max_digits=8)),
                ('money_out', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_input', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category_pk', models.IntegerField(blank=True, null=True)),
                ('upload_pk', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget_app_accounts.Account')),
            ],
        ),
        migrations.AddField(
            model_name='adjustment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='budget_app_accounts.Transaction'),
        ),
    ]
