# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 16:31
from __future__ import unicode_literals

import budget_app_uploads.functions
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget_app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_datetime', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_file', models.FileField(upload_to='uploads/', verbose_name='Upload')),
                ('archive_date', models.DateField(default=budget_app_uploads.functions.get_archive_date)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='budget_app_accounts.Account')),
            ],
        ),
    ]
